### ISSUE TITLE
locator / start locator

### ISSUE THREAD

**Issue by GiovaniJavier** [jxblum/pivotal-gemfire-clientserver-examples#5]
Hi
Analizingyour code I can see you configure gemfire in different ways, actually I have been configuring my application with Spring configuration like this:

@Configuration
public class GemfireConfiguration {
 
    @Bean
    Properties gemfireProperties() {
        Properties gemfireProperties = new Properties();
        gemfireProperties.setProperty("name","SpringDataGemFireApplication");
        gemfireProperties.setProperty("mcast-port", "0");
        gemfireProperties.setProperty("log-level", "config");
        return gemfireProperties;
    }
 
.....
}

My doubt, is not an issue, the locators??? 
I have to put a locator "localhost[1099]"
 I have been working on a gemfire client, with only one Region, I read so many blogs and many lines of information but it is not still clear, because I don't know if I have to put "start-locator" or "locator", I don't know if one is for gemfire server or for client and where can I put it. When I put in the Properties method "gemfireProperties.setProperty("locator", "localhost[1099]");"  I get an error because the spring cannot find the locator (it says is NULL), could you help me clarifying this doubt, please?

**Comment by jxblum** [comment]
Note, I answered your question in StackOverflow, here... https://stackoverflow.com/questions/51659771/start-locator-locators-which-is-for-client-and-which-is-for-server.

Let's resolve the conversation on SO please.
